const products = [
    // 1. Studio & Electronics (Total: 20)
    { name: 'Aura Pods Elite', image: '/images/headphones.png?v=10', description: 'Studio-grade over-ear headphones with active noise cancellation.', brand: 'Nexus Audio', category: 'Studio', price: 349, originalPrice: 429, discountPercentage: 20, countInStock: 25, rating: 4.9, numReviews: 128 },
    { name: 'Titan Phone 15', image: '/images/phone.png?v=10', description: 'The pinnacle of mobile innovation. Titanium chassis.', brand: 'Titan Tech', category: 'Studio', price: 1199, originalPrice: 1299, discountPercentage: 8, countInStock: 15, rating: 4.8, numReviews: 256 },
    { name: 'Titan Watch Ultra', image: '/images/titan_watch_pro.png?v=10', description: 'Advanced biometric tracking and rugged design.', brand: 'Titan Tech', category: 'Studio', price: 799, originalPrice: 899, discountPercentage: 11, countInStock: 15, rating: 4.5, numReviews: 88 },
    { name: 'Zenith RGB Keyboard', image: '/images/keyboard.png?v=10', description: 'Mechanical precision with customizable RGB lighting.', brand: 'KeyClick', category: 'Studio', price: 159, originalPrice: 159, discountPercentage: 0, countInStock: 30, rating: 4.9, numReviews: 120 },
    { name: 'SlimBook Ultra 14', image: '/images/laptop.png?v=10', description: 'Ultra-thin, ultra-powerful professional laptop.', brand: 'SlimBook', category: 'Studio', price: 899, originalPrice: 999, discountPercentage: 10, countInStock: 10, rating: 4.6, numReviews: 55 },
    { name: 'Silver Smartwatch', image: '/images/electronics_1.png?v=10', description: 'Elegant circular design with full health suite.', brand: 'Temporal', category: 'Studio', price: 350, originalPrice: 450, discountPercentage: 22, countInStock: 60, rating: 4.7, numReviews: 75 },
    { name: 'Creative Pen Tablet', image: '/images/electronics_2.png?v=10', description: 'Professional digital canvas with pressure stylus.', brand: 'Nexus Audio', category: 'Studio', price: 499, originalPrice: 599, discountPercentage: 16, countInStock: 200, rating: 4.5, numReviews: 412 },
    { name: 'Pro Gaming Mouse', image: '/images/electronics_5.png?v=10', description: 'High-precision sensor with RGB illumination.', brand: 'Nexus Audio', category: 'Studio', price: 89, originalPrice: 110, discountPercentage: 19, countInStock: 45, rating: 4.8, numReviews: 210 },
    { name: 'Nexus Studio Microphone', image: '/images/microphone.png?v=10', description: 'Broadcast-quality large-diaphragm capture.', brand: 'Nexus Audio', category: 'Studio', price: 249, originalPrice: 299, discountPercentage: 16, countInStock: 35, rating: 4.9, numReviews: 120 },
    { name: 'SoundShape Monitor', image: '/images/studio_1.png?v=10', description: 'Active studio speaker with transparent response.', brand: 'SoundShape', category: 'Studio', price: 540, originalPrice: 650, discountPercentage: 17, countInStock: 150, rating: 4.7, numReviews: 340 },
    { name: 'Studio Condenser Mic', image: '/images/studio_2.png?v=10', description: 'Large-capsule recording for pristine vocals.', brand: 'Nexus Audio', category: 'Studio', price: 320, originalPrice: 400, discountPercentage: 20, countInStock: 25, rating: 4.8, numReviews: 112 },
    { name: 'Audio Interface Pro', image: '/images/studio_3.png?v=10', description: 'High-fidelity external sound card for professionals.', brand: 'Nexus Audio', category: 'Studio', price: 450, originalPrice: 550, discountPercentage: 18, countInStock: 12, rating: 4.9, numReviews: 45 },
    { name: 'Vocal Master Mic', image: '/images/studio_4.png?v=10', description: 'Professional condenser microphone for high-end recordings.', brand: 'Nexus Audio', category: 'Studio', price: 680, originalPrice: 750, discountPercentage: 9, countInStock: 8, rating: 5.0, numReviews: 28 },
    { name: 'Reference Speakers', image: '/images/studio_5.png?v=10', description: 'True-to-life sound reproduction for mixing.', brand: 'SoundShape', category: 'Studio', price: 1200, originalPrice: 1400, discountPercentage: 14, countInStock: 5, rating: 4.8, numReviews: 19 },
    { name: 'Analog PolySynth', image: '/images/studio_6.png?v=10', description: 'Rich, warm analog tones for modern production.', brand: 'Nexus Audio', category: 'Studio', price: 2100, originalPrice: 2500, discountPercentage: 16, countInStock: 3, rating: 5.0, numReviews: 15 },
    { name: 'MIDI Master 88', image: '/images/studio_7.png?v=10', description: 'Full-weighted keyboard controller with deep integration.', brand: 'Nexus Audio', category: 'Studio', price: 850, originalPrice: 950, discountPercentage: 10, countInStock: 6, rating: 4.7, numReviews: 32 },
    { name: 'Low-End Subwoofer', image: '/images/studio_8.png?v=10', description: 'Deep, accurate bass extension for small rooms.', brand: 'SoundShape', category: 'Studio', price: 480, originalPrice: 550, discountPercentage: 12, countInStock: 10, rating: 4.6, numReviews: 24 },
    { name: 'Hardware Rack Unit', image: '/images/studio_9.png?v=10', description: 'Precision signal processing for studio signal chains.', brand: 'Nexus Audio', category: 'Studio', price: 1450, originalPrice: 1600, discountPercentage: 9, countInStock: 4, rating: 4.9, numReviews: 7 },
    { name: 'Pro Boom Stand', image: '/images/studio_10.png?v=10', description: 'Stable, adjustable microphone mounting for professionals.', brand: 'Nexus Audio', category: 'Studio', price: 180, originalPrice: 220, discountPercentage: 18, countInStock: 20, rating: 4.8, numReviews: 55 },
    { name: 'Acoustic Panel Diffuser', image: '/images/studio_11.png?v=10', description: 'Scientific sound treatment for critical listening.', brand: 'Lumina Design', category: 'Studio', price: 95, originalPrice: 120, discountPercentage: 20, countInStock: 50, rating: 4.7, numReviews: 88 },
    { name: 'Isolation Vocal Booth', image: '/images/studio_12.png?v=10', description: 'Portable acoustic isolation for pristine captures.', brand: 'SoundShape', category: 'Studio', price: 3200, originalPrice: 3800, discountPercentage: 15, countInStock: 2, rating: 5.0, numReviews: 4 },

    // 2. Optics (Total: 15)
    { name: 'Lumina Vision Pro', image: '/images/telescope.png?v=10', description: 'Cinematic clarity with a premium carbon fiber body.', brand: 'Visionary', category: 'Optics', price: 2499, originalPrice: 2799, discountPercentage: 10, countInStock: 10, rating: 5.0, numReviews: 42 },
    { name: 'Alpha Pro Mirrorless', image: '/images/electronics_3.png?v=10', description: 'Professional full-frame camera for cinematic capture.', brand: 'Visionary', category: 'Optics', price: 3200, originalPrice: 3500, discountPercentage: 9, countInStock: 5, rating: 4.9, numReviews: 76 },
    { name: 'Horizon 4K Drone', image: '/images/electronics_4.png?v=10', description: 'Stunning 4K resolution aerial photography.', brand: 'Visionary', category: 'Optics', price: 899, originalPrice: 999, discountPercentage: 10, countInStock: 12, rating: 4.9, numReviews: 88 },
    { name: 'Digital Microscope', image: '/images/optics_1.png?v=10', description: 'Laboratory-grade digital imaging system.', brand: 'Visionary', category: 'Optics', price: 1200, originalPrice: 1500, discountPercentage: 20, countInStock: 100, rating: 4.8, numReviews: 320 },
    { name: 'Stellar Binoculars', image: '/images/binoculars.png?v=10', description: 'High-magnification for celestial observation.', brand: 'Visionary', category: 'Optics', price: 245, originalPrice: 280, discountPercentage: 12, countInStock: 45, rating: 4.9, numReviews: 89 },
    { name: 'Astro Observatory', image: '/images/optics_2.png?v=10', description: 'Advanced telescope system for deep space.', brand: 'Visionary', category: 'Optics', price: 5200, originalPrice: 6000, discountPercentage: 13, countInStock: 85, rating: 4.6, numReviews: 178 },
    { name: 'Tactical Night Vision', image: '/images/optics_3.png?v=10', description: 'Military-grade ocular enhancement system.', brand: 'Visionary', category: 'Optics', price: 1800, originalPrice: 2200, discountPercentage: 18, countInStock: 10, rating: 4.9, numReviews: 12 },
    { name: 'Advanced Refractor', image: '/images/optics_4.png?v=10', description: 'Precision refractor for planetary observation.', brand: 'Visionary', category: 'Optics', price: 1450, originalPrice: 1600, discountPercentage: 9, countInStock: 8, rating: 4.8, numReviews: 31 },
    { name: 'Long-Range Binos', image: '/images/optics_5.png?v=10', description: 'Unmatched distance for nature and exploration.', brand: 'Visionary', category: 'Optics', price: 420, originalPrice: 480, discountPercentage: 12, countInStock: 15, rating: 4.7, numReviews: 64 },
    { name: 'Lab Grade Microscope', image: '/images/optics_6.png?v=10', description: 'High powered biological imaging system.', brand: 'Visionary', category: 'Optics', price: 2800, originalPrice: 3200, discountPercentage: 12, countInStock: 4, rating: 4.9, numReviews: 12 },
    { name: 'Camo Spotting Scope', image: '/images/optics_7.png?v=10', description: 'Stealth design for outdoor wildlife scouting.', brand: 'Visionary', category: 'Optics', price: 890, originalPrice: 1100, discountPercentage: 19, countInStock: 10, rating: 4.6, numReviews: 42 },
    { name: 'Precision Optical Prism', image: '/images/optics_8.png?v=10', description: 'Scientifically crafted light diffraction gear.', brand: 'Visionary', category: 'Optics', price: 140, originalPrice: 180, discountPercentage: 22, countInStock: 40, rating: 4.5, numReviews: 112 },
    { name: 'Thermal Imaging Unit', image: '/images/optics_9.png?v=10', description: 'Advanced heat detection for security and rescue.', brand: 'Visionary', category: 'Optics', price: 3500, originalPrice: 4000, discountPercentage: 12, countInStock: 3, rating: 5.0, numReviews: 8 },
    { name: 'Macro Photography Lens', image: '/images/optics_10.png?v=10', description: 'Extreme detail for small-scale photography.', brand: 'Visionary', category: 'Optics', price: 1250, originalPrice: 1500, discountPercentage: 16, countInStock: 5, rating: 4.9, numReviews: 54 },

    // 3. Furniture (Total: 9)
    { name: 'Eames Silhouette Sofa', image: '/images/sofa.png?v=10', description: 'An icon of mid-century design. Premium leather.', brand: 'Heritage Home', category: 'Furniture', price: 1250, originalPrice: 1500, discountPercentage: 16, countInStock: 5, rating: 4.9, numReviews: 24 },
    { name: 'Zenith Minimalist Desk', image: '/images/desk.png?v=10', description: 'Sustainable Nordic oak with hidden cable management.', brand: 'Heritage Home', category: 'Furniture', price: 850, originalPrice: 950, discountPercentage: 10, countInStock: 12, rating: 4.8, numReviews: 38 },
    { name: 'Lunar Orbital Lamp', image: '/images/lamp.png?v=10', description: 'Sculptural lighting with hand-blown frosted glass.', brand: 'Lumina Design', category: 'Furniture', price: 220, originalPrice: 280, discountPercentage: 21, countInStock: 30, rating: 4.6, numReviews: 85 },
    { name: 'Velvet Emerald Chair', image: '/images/furniture_2.png?v=10', description: 'Luxury tufted armchair in deep emerald velvet.', brand: 'Heritage Home', category: 'Furniture', price: 1200, originalPrice: 1500, discountPercentage: 20, countInStock: 4, rating: 4.9, numReviews: 15 },
    { name: 'Rustic Timber Table', image: '/images/furniture_3.png?v=10', description: 'Hand-crafted solid wood coffee table.', brand: 'Heritage Home', category: 'Furniture', price: 650, originalPrice: 750, discountPercentage: 13, countInStock: 7, rating: 4.7, numReviews: 10 },
    { name: 'Floating Oak Shelf', image: '/images/furniture_4.png?v=10', description: 'Minimalist wall-mounted storage solution.', brand: 'Heritage Home', category: 'Furniture', price: 320, originalPrice: 400, discountPercentage: 20, countInStock: 25, rating: 4.6, numReviews: 30 },
    { name: 'Nordic Ergo Chair', image: '/images/chair.png?v=10', description: 'Professional mesh chair with lumbar support.', brand: 'Heritage Home', category: 'Furniture', price: 450, originalPrice: 550, discountPercentage: 18, countInStock: 15, rating: 4.8, numReviews: 42 },
    { name: 'Minimalist Platform Bed', image: '/images/furniture_1.png?v=10', description: 'Sleek wooden frame with breathable base.', brand: 'Heritage Home', category: 'Furniture', price: 1450, originalPrice: 1800, discountPercentage: 19, countInStock: 75, rating: 4.9, numReviews: 125 },

    // 4. Wear & Lifestyle (Total: 10)
    { name: 'Obsidian Tech Jacket', image: '/images/jacket.png?v=10', description: 'The future of utility. Triple-layered Gore-Tex Pro.', brand: 'Apex Outdoor', category: 'Wear', price: 549, originalPrice: 650, discountPercentage: 15, countInStock: 20, rating: 4.9, numReviews: 64 },
    { name: 'Merino Precision Knit', image: '/images/merino_knit.png?v=10', description: 'Engineered comfort. Fine New Zealand Merino wool.', brand: 'Apex Outdoor', category: 'Wear', price: 180, originalPrice: 180, discountPercentage: 0, countInStock: 45, rating: 4.7, numReviews: 112 },
    { name: 'Urban Tech Hoodie', image: '/images/apparel_1.png?v=10', description: 'Heavyweight cotton hoodie with a modern fit.', brand: 'Apex Outdoor', category: 'Wear', price: 120, originalPrice: 150, discountPercentage: 20, countInStock: 20, rating: 5.0, numReviews: 12 },
    { name: 'Apex Pro Runners', image: '/images/shoes.png?v=10', description: 'High-performance foam for maximum energy return.', brand: 'Apex Outdoor', category: 'Wear', price: 185, originalPrice: 220, discountPercentage: 16, countInStock: 60, rating: 4.7, numReviews: 145 },
    { name: 'Aero Aviator Glass', image: '/images/lifestyle_1.png?v=10', description: 'Classic aviator frame with polarized protection.', brand: 'Visionary', category: 'Wear', price: 140, originalPrice: 160, discountPercentage: 12, countInStock: 50, rating: 4.4, numReviews: 200 },
    { name: 'Equinox Chronograph', image: '/images/watch.png?v=10', description: 'Precision timing for the modern explorer.', brand: 'Temporal', category: 'Lifestyle', price: 890, originalPrice: 1100, discountPercentage: 19, countInStock: 8, rating: 4.8, numReviews: 31 },
    { name: 'Metropolis Weekender', image: '/images/backpack.png?v=10', description: 'The ultimate travel companion. Full-grain leather.', brand: 'Metro Craft', category: 'Lifestyle', price: 420, originalPrice: 420, discountPercentage: 0, countInStock: 18, rating: 4.5, numReviews: 22 },
    { name: 'Aura Smart Bottle', image: '/images/lifestyle_3.png?v=10', description: 'Hydration tracking with a glowing smart base.', brand: 'Nexus Audio', category: 'Lifestyle', price: 85, originalPrice: 110, discountPercentage: 22, countInStock: 40, rating: 4.5, numReviews: 48 },
    { name: 'Leather Card Wallet', image: '/images/lifestyle_2.png?v=10', description: 'Full-grain leather with dedicated RFID protection.', brand: 'Metro Craft', category: 'Lifestyle', price: 85, originalPrice: 110, discountPercentage: 22, countInStock: 60, rating: 4.7, numReviews: 154 }
];

export default products;
