const products = [
    // --- ELECTRONICS ---
    {
        name: 'Aura Pods Elite',
        image: 'https://picsum.photos/seed/aura-pods/800/600',
        description: 'Bespoke audio engineering meets cinematic soundstage. Features 40dB active noise cancellation and 48-hour endurance.',
        brand: 'Nexus Audio',
        category: 'Electronics',
        price: 349.00,
        originalPrice: 429.00,
        discountPercentage: 20,
        countInStock: 25,
        rating: 4.9,
        numReviews: 128,
        specifications: { 'ANC': 'Up to 40dB', 'Battery': '48h', 'Drivers': '50mm Titanium' }
    },
    {
        name: 'Titan Phone 15',
        image: 'https://picsum.photos/seed/titan-phone/800/600',
        description: 'The pinnacle of mobile innovation. Aerospacial titanium chassis with the world\'s most advanced 3nm processor.',
        brand: 'Titan Tech',
        category: 'Electronics',
        price: 1199.00,
        originalPrice: 1299.00,
        discountPercentage: 8,
        countInStock: 15,
        rating: 4.8,
        numReviews: 256,
        specifications: { 'Display': '6.7" OLED', 'Processor': 'A17 Ultra', 'Camera': '48MP Triple' }
    },
    {
        name: 'Lumina Vision Pro',
        image: 'https://picsum.photos/seed/lumina-vision/800/600',
        description: 'Cinematic clarity in every frame. 8K resolution with deep-learning HDR enhancement for the ultimate theater experience.',
        brand: 'Visionary',
        category: 'Optics',
        price: 2499.00,
        originalPrice: 2799.00,
        discountPercentage: 10,
        countInStock: 10,
        rating: 5.0,
        numReviews: 42,
        specifications: { 'Resolution': '8K Ultra HD', 'Panel': 'Mini-LED', 'Brightness': '2000 nits' }
    },
    {
        name: 'Zenith Game Console',
        image: 'https://picsum.photos/seed/zenith-console/800/600',
        description: 'Next-generation performance. Liquid-cooled architecture capable of 120fps gaming at 4K resolution.',
        brand: 'Zenith Interactive',
        category: 'Electronics',
        price: 499.00,
        originalPrice: 599.00,
        discountPercentage: 15,
        countInStock: 40,
        rating: 4.7,
        numReviews: 512,
        specifications: { 'Output': '4K 120Hz', 'SSD': '2TB Gen5', 'Ram': '32GB' }
    },

    // --- FURNITURE ---
    {
        name: 'Eames Silhouette Lounge',
        image: 'https://picsum.photos/seed/eames-lounge/800/600',
        description: 'An icon of mid-century design. Hand-assembled with premium Italian leather and walnut veneers.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 1250.00,
        originalPrice: 1500.00,
        discountPercentage: 16,
        countInStock: 5,
        rating: 4.9,
        numReviews: 24,
        specifications: { 'Material': 'Italian Leather', 'Frame': 'Walnut Wood', 'Type': 'Lounge' }
    },
    {
        name: 'Zenith Minimalist Desk',
        image: 'https://picsum.photos/seed/zenith-desk/800/600',
        description: 'The foundation of your productivity. Crafted from a single slab of sustainable Nordic oak with hidden cable management.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 850.00,
        originalPrice: 950.00,
        discountPercentage: 10,
        countInStock: 12,
        rating: 4.8,
        numReviews: 38,
        specifications: { 'Wood': 'Nordic Oak', 'Width': '160cm', 'Depth': '80cm' }
    },
    {
        name: 'Lunar Orbital Lamp',
        image: 'https://picsum.photos/seed/lunar-lamp/800/600',
        description: 'Sculptural lighting inspired by celestial bodies. Warm ambient glow through hand-blown frosted glass.',
        brand: 'Lumina Design',
        category: 'Furniture',
        price: 220.00,
        originalPrice: 280.00,
        discountPercentage: 21,
        countInStock: 30,
        rating: 4.6,
        numReviews: 85,
        specifications: { 'Bulb': 'LED (Replaceable)', 'Material': 'Frosted Glass', 'Base': 'Brass' }
    },

    // --- APPAREL ---
    {
        name: 'Obsidian Tech Jacket',
        image: 'https://picsum.photos/seed/obsidian-jacket/800/600',
        description: 'The future of utility. Triple-layered Gore-Tex Pro shell with internal thermal regulation and magnetic security pockets.',
        brand: 'Apex Outdoor',
        category: 'Apparel',
        price: 549.00,
        originalPrice: 650.00,
        discountPercentage: 15,
        countInStock: 20,
        rating: 4.9,
        numReviews: 64,
        specifications: { 'Shell': 'Gore-Tex Pro', 'Fit': 'Ergonomic', 'Pockets': '8 External' }
    },
    {
        name: 'Merino Precision Knit',
        image: 'https://picsum.photos/seed/merino-knit/800/600',
        description: 'Engineered comfort. Sourced from the finest New Zealand Merino wool for unparalleled breathability and softness.',
        brand: 'Apex Outdoor',
        category: 'Apparel',
        price: 180.00,
        originalPrice: 180.00,
        discountPercentage: 0,
        countInStock: 45,
        rating: 4.7,
        numReviews: 112,
        specifications: { 'Material': '100% Merino', 'Weight': '200gsm', 'Origin': 'NZ' }
    },

    // --- LIFESTYLE ---
    {
        name: 'Equinox Chrono X',
        image: 'https://picsum.photos/seed/equinox-chrono/800/600',
        description: 'Precision timing for the modern explorer. Automatic movement with sapphire crystal and 100m water resistance.',
        brand: 'Temporal',
        category: 'Lifestyle',
        price: 890.00,
        originalPrice: 1100.00,
        discountPercentage: 19,
        countInStock: 8,
        rating: 4.8,
        numReviews: 31,
        specifications: { 'Movement': 'Automatic', 'Crystal': 'Sapphire', 'Water': '100m' }
    },
    {
        name: 'Metropolis Weekender',
        image: 'https://picsum.photos/seed/metropolis-bag/800/600',
        description: 'The ultimate travel companion. Full-grain leather with brass hardware and a dedicated compartment for essentials.',
        brand: 'Metro Craft',
        category: 'Lifestyle',
        price: 420.00,
        originalPrice: 420.00,
        discountPercentage: 0,
        countInStock: 18,
        rating: 4.5,
        numReviews: 22,
        specifications: { 'Material': 'Full Grain Leather', 'Volume': '45L', 'Weight': '2.2kg' }
    },

    // --- ADDITIONAL MASS DATA ---
    {
        name: 'Titan Watch Pro',
        image: 'https://picsum.photos/seed/titan-watch/800/600',
        description: 'The ultimate smartwatch for athletes. High-precision GPS and biometric sensors.',
        brand: 'Titan Tech',
        category: 'Electronics',
        price: 299.99,
        originalPrice: 349.99,
        discountPercentage: 15,
        countInStock: 15,
        rating: 4.5,
        numReviews: 88,
        specifications: { 'Display': 'AMOLED', 'Battery': '14 days' }
    },
    {
        name: 'Zenith Keyboard',
        image: 'https://picsum.photos/seed/zenith-keyboard/800/600',
        description: 'Mechanical precision. Customizable RGB and ultra-responsive switches.',
        brand: 'KeyClick',
        category: 'Electronics',
        price: 159.99,
        originalPrice: 159.99,
        discountPercentage: 0,
        countInStock: 30,
        rating: 4.9,
        numReviews: 120,
        specifications: { 'Switches': 'Cherry MX Blue' }
    },
    {
        name: 'SlimBook Ultra 14',
        image: 'https://picsum.photos/seed/slimbook-laptop/800/600',
        description: 'Ultra-thin, ultra-powerful. The perfect laptop for creative professionals.',
        brand: 'SlimBook',
        category: 'Electronics',
        price: 899.99,
        originalPrice: 999.99,
        discountPercentage: 10,
        countInStock: 10,
        rating: 4.6,
        numReviews: 55,
        specifications: { 'Processor': 'Intel i7', 'RAM': '16GB' }
    },
    {
        name: 'Velvet Cloud Sofa',
        image: 'https://picsum.photos/seed/velvet-sofa/800/600',
        description: 'Sink into pure luxury. High-density foam wrapped in premium velvet.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 1800.00,
        originalPrice: 2200.00,
        discountPercentage: 18,
        countInStock: 4,
        rating: 4.9,
        numReviews: 15,
        specifications: { 'Material': 'Velvet', 'Color': 'Deep Blue' }
    },
    {
        name: 'Onyx Coffee Table',
        image: 'https://picsum.photos/seed/onyx-table/800/600',
        description: 'A statement piece for your living room. Hand-polished onyx stone.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 650.00,
        originalPrice: 750.00,
        discountPercentage: 13,
        countInStock: 7,
        rating: 4.7,
        numReviews: 10,
        specifications: { 'Stone': 'Onyx', 'Base': 'Steel' }
    },
    {
        name: 'Silk Drapery Set',
        image: 'https://picsum.photos/seed/silk-drapery/800/600',
        description: 'Elegant window treatments. 100% pure silk with black-out lining.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 320.00,
        originalPrice: 400.00,
        discountPercentage: 20,
        countInStock: 25,
        rating: 4.6,
        numReviews: 30,
        specifications: { 'Material': 'Silk', 'Lining': 'Thermal' }
    },
    {
        name: 'Cashmere Overcoat',
        image: 'https://picsum.photos/seed/cashmere-coat/800/600',
        description: 'Timeless sophistication. Italian cashmere with a modern slim fit.',
        brand: 'Apex Outdoor',
        category: 'Apparel',
        price: 750.00,
        originalPrice: 850.00,
        discountPercentage: 11,
        countInStock: 10,
        rating: 5.0,
        numReviews: 12,
        specifications: { 'Material': '100% Cashmere', 'Fit': 'Slim' }
    },
    {
        name: 'Urban Cargo Joggers',
        image: 'https://picsum.photos/seed/cargo-joggers/800/600',
        description: 'Functional streetwear. Water-resistant stretch fabric with utility pockets.',
        brand: 'Apex Outdoor',
        category: 'Apparel',
        price: 140.00,
        originalPrice: 160.00,
        discountPercentage: 12,
        countInStock: 50,
        rating: 4.4,
        numReviews: 200,
        specifications: { 'Stretch': '4-Way', 'Finish': 'DWR' }
    },
    {
        name: 'Nomad Canvas Backpack',
        image: 'https://picsum.photos/seed/nomad-backpack/800/600',
        description: 'Rugged durability for every journey. Waxed canvas with leather reinforcements.',
        brand: 'Metro Craft',
        category: 'Lifestyle',
        price: 185.00,
        originalPrice: 210.00,
        discountPercentage: 12,
        countInStock: 40,
        rating: 4.5,
        numReviews: 48,
        specifications: { 'Material': 'Waxed Canvas', 'Size': '25L' }
    },
    {
        name: 'Nordic Scent Set',
        image: 'https://picsum.photos/seed/nordic-scent/800/600',
        description: 'A sensory journey through the arctic. Hand-poured soy candles with essential oils.',
        brand: 'Lumina Design',
        category: 'Lifestyle',
        price: 65.00,
        originalPrice: 75.00,
        discountPercentage: 13,
        countInStock: 100,
        rating: 4.8,
        numReviews: 320,
        specifications: { 'Wax': 'Soy', 'Scent': 'Cedar & Sea Salt' }
    },
    {
        name: 'Aerospace Aviators',
        image: 'https://picsum.photos/seed/aerospace-aviators/800/600',
        description: 'Classic frame, modern lens technology. Polarized protection for the urban sky.',
        brand: 'Visionary',
        category: 'Optics',
        price: 155.00,
        originalPrice: 195.00,
        discountPercentage: 20,
        countInStock: 60,
        rating: 4.7,
        numReviews: 75,
        specifications: { 'Lens': 'Polarized', 'Frame': 'Stainless' }
    },
    {
        name: 'Eclipse Smart Lenses',
        image: 'https://picsum.photos/seed/eclipse-lenses/800/600',
        description: 'Augmented reality meets everyday eyewear. Seamless HUD integration.',
        brand: 'Visionary',
        category: 'Optics',
        price: 499.00,
        originalPrice: 599.00,
        discountPercentage: 16,
        countInStock: 20,
        rating: 4.8,
        numReviews: 45,
        specifications: { 'Display': 'Micro-OLED', 'Battery': '18h' }
    },
    {
        name: 'Nexus Studio Condenser Mic',
        image: 'https://picsum.photos/seed/nexus-mic/800/600',
        description: 'Broadcast-quality audio capture. Features a large-diaphragm gold-sputtered capsule.',
        brand: 'Nexus Audio',
        category: 'Electronics',
        price: 249.00,
        originalPrice: 299.00,
        discountPercentage: 16,
        countInStock: 35,
        rating: 4.9,
        numReviews: 120,
        specifications: { 'Pattern': 'Cardioid', 'Connection': 'XLR' }
    },
    {
        name: 'Aero Dynamic T-Shirt',
        image: 'https://picsum.photos/seed/aero-tshirt/800/600',
        description: 'Ultra-lightweight moisture-wicking fabric for peak performance.',
        brand: 'Apex Outdoor',
        category: 'Apparel',
        price: 45.00,
        originalPrice: 55.00,
        discountPercentage: 18,
        countInStock: 100,
        rating: 4.6,
        numReviews: 89,
        specifications: { 'Material': 'Aero-Blend', 'Fit': 'Athletic' }
    },
    {
        name: 'Minimalist Aluminum Pen',
        image: 'https://picsum.photos/seed/alum-pen/800/600',
        description: 'Precision-machined from aerospace-grade aluminum. A writer\'s essential.',
        brand: 'Metro Craft',
        category: 'Lifestyle',
        price: 75.00,
        originalPrice: 85.00,
        discountPercentage: 11,
        countInStock: 60,
        rating: 4.7,
        numReviews: 154,
        specifications: { 'Material': 'Aluminum', 'Ink': 'Black Rollerball' }
    },
    {
        name: 'Nordic Ergo Chair',
        image: 'https://picsum.photos/seed/nordic-chair/800/600',
        description: 'Ergonomic perfection meets Scandinavian minimalism. Breathable mesh back.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 450.00,
        originalPrice: 550.00,
        discountPercentage: 18,
        countInStock: 15,
        rating: 4.8,
        numReviews: 42,
        specifications: { 'Support': 'Lumbar', 'Base': 'Aluminum' }
    },
    {
        name: 'Quantum Noise-Cancelling Headphones',
        image: 'https://picsum.photos/seed/quantum-headphones/800/600',
        description: 'Immersive audio experience with active noise cancellation and ergonomic fit.',
        brand: 'Nexus Audio',
        category: 'Electronics',
        price: 299.00,
        originalPrice: 350.00,
        discountPercentage: 15,
        countInStock: 45,
        rating: 4.8,
        numReviews: 210,
        specifications: { 'ANC': 'Active', 'Battery': '30h' }
    },
    {
        name: 'Horizon Drone Camera',
        image: 'https://picsum.photos/seed/horizon-drone/800/600',
        description: 'Capture sweeping landscapes from the sky in stunning 4K resolution.',
        brand: 'Visionary',
        category: 'Optics',
        price: 899.00,
        originalPrice: 999.00,
        discountPercentage: 10,
        countInStock: 12,
        rating: 4.9,
        numReviews: 88,
        specifications: { 'Camera': '4K HDR', 'Flight Time': '45m' }
    },
    {
        name: 'Apex Trekking Boots',
        image: 'https://picsum.photos/seed/apex-boots/800/600',
        description: 'Built for the toughest trails. Waterproof, breathable, and incredibly durable.',
        brand: 'Apex Outdoor',
        category: 'Apparel',
        price: 185.00,
        originalPrice: 220.00,
        discountPercentage: 16,
        countInStock: 60,
        rating: 4.7,
        numReviews: 145,
        specifications: { 'Material': 'Gore-Tex', 'Sole': 'Vibram' }
    },
    {
        name: 'Chronos Minimalist Watch',
        image: 'https://picsum.photos/seed/chronos-watch/800/600',
        description: 'Less is more. A beautiful everyday watch featuring an ultra-slim profile.',
        brand: 'Temporal',
        category: 'Lifestyle',
        price: 150.00,
        originalPrice: 150.00,
        discountPercentage: 0,
        countInStock: 80,
        rating: 4.6,
        numReviews: 230,
        specifications: { 'Movement': 'Quartz', 'Case': 'Titanium' }
    },
    {
        name: 'Lumina Smart LED Strip',
        image: 'https://picsum.photos/seed/led-strip/800/600',
        description: 'Transform your space with customizable 16 million colors and app control.',
        brand: 'Lumina Design',
        category: 'Electronics',
        price: 49.00,
        originalPrice: 65.00,
        discountPercentage: 25,
        countInStock: 200,
        rating: 4.5,
        numReviews: 412,
        specifications: { 'Length': '5m', 'Connectivity': 'Wi-Fi/Bluetooth' }
    },
    {
        name: 'AURA Home Scent Diffuser',
        image: 'https://picsum.photos/seed/aura-diffuser/800/600',
        description: 'Elevate your environment. Ultrasonic diffusion of essential oils for a calming atmosphere.',
        brand: 'Lumina Design',
        category: 'Lifestyle',
        price: 85.00,
        originalPrice: 100.00,
        discountPercentage: 15,
        countInStock: 50,
        rating: 4.8,
        numReviews: 125,
        specifications: { 'Capacity': '300ml', 'Timer': 'Up to 8h' }
    },
    {
        name: 'Obsidian Workstation Desk',
        image: 'https://picsum.photos/seed/obsidian-desk/800/600',
        description: 'The ultimate modern desk. Solid carbon fiber top with adjustable standing height.',
        brand: 'Heritage Home',
        category: 'Furniture',
        price: 1199.00,
        originalPrice: 1399.00,
        discountPercentage: 14,
        countInStock: 10,
        rating: 4.9,
        numReviews: 65,
        specifications: { 'Top': 'Carbon Fiber', 'Motors': 'Dual' }
    },
    {
        name: 'Voyager Travel Sling',
        image: 'https://picsum.photos/seed/voyager-sling/800/600',
        description: 'Compact and secure carrying for everyday essentials while on the move.',
        brand: 'Metro Craft',
        category: 'Apparel',
        price: 65.00,
        originalPrice: 80.00,
        discountPercentage: 18,
        countInStock: 120,
        rating: 4.7,
        numReviews: 310,
        specifications: { 'Material': 'Ballistic Nylon', 'Capacity': '5L' }
    },
    {
        name: 'Prism Macro Lens Kit',
        image: 'https://picsum.photos/seed/prism-macro/800/600',
        description: 'Professional-grade attachable lenses for capturing microscopic details on your smartphone.',
        brand: 'Visionary',
        category: 'Optics',
        price: 120.00,
        originalPrice: 150.00,
        discountPercentage: 20,
        countInStock: 85,
        rating: 4.6,
        numReviews: 178,
        specifications: { 'Lenses': 'Macro, Wide, Fisheye', 'Mount': 'Universal Clip' }
    },
    // --- STUDIO & OPTICS ---
    {
        name: 'Studio Pro Interface',
        image: 'https://picsum.photos/seed/studio-interface/800/600',
        description: 'Professional 2-in/4-out USB audio interface for pristine studio recording.',
        brand: 'Nexus Audio',
        category: 'Studio',
        price: 199.00,
        originalPrice: 249.00,
        discountPercentage: 20,
        countInStock: 25,
        rating: 4.8,
        numReviews: 112,
        specifications: { 'Inputs': '2x XLR/TRS', 'Resolution': '192kHz' }
    },
    {
        name: 'Acoustic Foam Panels',
        image: 'https://picsum.photos/seed/acoustic-foam/800/600',
        description: 'Premium sound absorption panels for your home studio setup.',
        brand: 'SoundShape',
        category: 'Studio',
        price: 89.00,
        originalPrice: 110.00,
        discountPercentage: 19,
        countInStock: 150,
        rating: 4.7,
        numReviews: 340,
        specifications: { 'Material': 'High-density foam', 'Size': '12x12 inches' }
    },
    {
        name: 'Stellar Binoculars',
        image: 'https://picsum.photos/seed/stellar-binos/800/600',
        description: 'High-magnification binoculars for bird watching and celestial observation.',
        brand: 'Visionary',
        category: 'Optics',
        price: 245.00,
        originalPrice: 280.00,
        discountPercentage: 12,
        countInStock: 45,
        rating: 4.9,
        numReviews: 89,
        specifications: { 'Magnification': '10x', 'Lens': '50mm' }
    },
    {
        name: 'Telescope Pro',
        image: 'https://picsum.photos/seed/telescope-pro/800/600',
        description: 'Deep-space viewing with our most powerful consumer telescope yet.',
        brand: 'Visionary',
        category: 'Optics',
        price: 650.00,
        originalPrice: 750.00,
        discountPercentage: 13,
        countInStock: 10,
        rating: 4.8,
        numReviews: 42,
        specifications: { 'Aperture': '130mm', 'Focal Length': '650mm' }
    },
    {
        name: 'Ergonomic Wear Tech Hoodie',
        image: 'https://picsum.photos/seed/tech-hoodie/800/600',
        description: 'Cutting edge fabric tech meets everyday comfort.',
        brand: 'Apex Outdoor',
        category: 'Wear',
        price: 95.00,
        originalPrice: 120.00,
        discountPercentage: 20,
        countInStock: 80,
        rating: 4.7,
        numReviews: 215,
        specifications: { 'Material': 'Tech Fleece', 'Fit': 'Relaxed' }
    },
    {
        name: 'Performance Running Shoes',
        image: 'https://picsum.photos/seed/running-shoes/800/600',
        description: 'Ultra-lightweight running shoes engineered for speed and endurance.',
        brand: 'Apex Outdoor',
        category: 'Wear',
        price: 135.00,
        originalPrice: 150.00,
        discountPercentage: 10,
        countInStock: 60,
        rating: 4.9,
        numReviews: 312,
        specifications: { 'Weight': '210g', 'Drop': '8mm' }
    },
    {
        name: 'Smart Water Bottle',
        image: 'https://picsum.photos/seed/smart-bottle/800/600',
        description: 'Tracks your hydration and glows to remind you to drink.',
        brand: 'Lumina Design',
        category: 'Lifestyle',
        price: 45.00,
        originalPrice: 60.00,
        discountPercentage: 25,
        countInStock: 150,
        rating: 4.6,
        numReviews: 405,
        specifications: { 'Capacity': '750ml', 'Battery': '30 Days' }
    },
    {
        name: 'Zen Meditation Cushion',
        image: 'https://picsum.photos/seed/zen-cushion/800/600',
        description: 'Ergonomic buckwheat-filled cushion for proper posture during meditation.',
        brand: 'Heritage Home',
        category: 'Lifestyle',
        price: 55.00,
        originalPrice: 65.00,
        discountPercentage: 15,
        countInStock: 80,
        rating: 4.8,
        numReviews: 290,
        specifications: { 'Filling': 'Buckwheat Hulls', 'Cover': 'Organic Cotton' }
    },
    {
        name: 'Studio Monitor Speakers',
        image: 'https://picsum.photos/seed/studio-monitors/800/600',
        description: 'Active 2-way studio monitors with precise frequency response.',
        brand: 'Nexus Audio',
        category: 'Studio',
        price: 349.00,
        originalPrice: 400.00,
        discountPercentage: 12,
        countInStock: 20,
        rating: 4.9,
        numReviews: 88,
        specifications: { 'Woofer': '5 inch Kevlar', 'Tweeter': '1 inch Silk Dome' }
    },
    {
        name: 'Desk Boom Arm',
        image: 'https://picsum.photos/seed/boom-arm/800/600',
        description: 'Professional articulated mic boom arm with hidden cable management.',
        brand: 'SoundShape',
        category: 'Studio',
        price: 120.00,
        originalPrice: 150.00,
        discountPercentage: 20,
        countInStock: 50,
        rating: 4.8,
        numReviews: 145,
        specifications: { 'Material': 'Aluminum', 'Reach': '32 inches' }
    },
    {
        name: 'Microscope Elite',
        image: 'https://picsum.photos/seed/microscope-elite/800/600',
        description: 'Digital binocular microscope with maximum 2000x magnification.',
        brand: 'Visionary',
        category: 'Optics',
        price: 850.00,
        originalPrice: 950.00,
        discountPercentage: 10,
        countInStock: 8,
        rating: 4.7,
        numReviews: 50,
        specifications: { 'Magnification': '40x - 2000x', 'Camera': '5MP' }
    },
    {
        name: 'Rangefinder Pro',
        image: 'https://picsum.photos/seed/rangefinder-pro/800/600',
        description: 'Laser rangefinder for golf, hunting and precise distance measurements.',
        brand: 'Visionary',
        category: 'Optics',
        price: 210.00,
        originalPrice: 249.00,
        discountPercentage: 15,
        countInStock: 30,
        rating: 4.8,
        numReviews: 120,
        specifications: { 'Range': '1000 Yards', 'Accuracy': '±1 Yard' }
    },
    {
        name: 'All-Weather Tech Jacket',
        image: 'https://picsum.photos/seed/allweather-jacket/800/600',
        description: 'Waterproof and breathable smart jacket for extreme conditions.',
        brand: 'Apex Outdoor',
        category: 'Wear',
        price: 280.00,
        originalPrice: 320.00,
        discountPercentage: 12,
        countInStock: 40,
        rating: 4.9,
        numReviews: 310,
        specifications: { 'Material': 'Gore-Tex Pro', 'Weight': 'Ultra-light' }
    },
    {
        name: 'Compression Tights',
        image: 'https://picsum.photos/seed/compression-tights/800/600',
        description: 'Performance tights for faster recovery and enhanced muscle support.',
        brand: 'Apex Outdoor',
        category: 'Wear',
        price: 85.00,
        originalPrice: 110.00,
        discountPercentage: 22,
        countInStock: 100,
        rating: 4.6,
        numReviews: 198,
        specifications: { 'Material': 'Spandex Blend', 'Care': 'Machine Wash' }
    },
    {
        name: 'Sunrise Alarm Clock',
        image: 'https://picsum.photos/seed/sunrise-clock/800/600',
        description: 'Wake up naturally with a simulated sunrise and relaxing sounds.',
        brand: 'Lumina Design',
        category: 'Lifestyle',
        price: 95.00,
        originalPrice: 130.00,
        discountPercentage: 26,
        countInStock: 60,
        rating: 4.7,
        numReviews: 450,
        specifications: { 'Light': 'LED 300 Lux', 'Sounds': '7 Nature Sounds' }
    },
    {
        name: 'Ceramic Pour Over Set',
        image: 'https://picsum.photos/seed/pour-over/800/600',
        description: 'Minimalist pour over coffee maker for the perfect morning brew.',
        brand: 'Heritage Home',
        category: 'Lifestyle',
        price: 65.00,
        originalPrice: 80.00,
        discountPercentage: 18,
        countInStock: 75,
        rating: 4.9,
        numReviews: 125,
        specifications: { 'Material': 'Ceramic', 'Capacity': '600ml' }
    }
];

const targetCategories = ['Studio', 'Optics', 'Wear', 'Lifestyle'];
const brands = ['Nexus Audio', 'Visionary', 'Apex Outdoor', 'Lumina Design', 'Heritage Home', 'SoundShape', 'Metro Craft', 'Temporal'];

// Picsum seeds — unique seed = unique image, always works, never expires
const categoryImages: Record<string, string[]> = {
    "Studio": [
        "https://picsum.photos/seed/studio-01/800/600",
        "https://picsum.photos/seed/studio-02/800/600",
        "https://picsum.photos/seed/studio-03/800/600",
        "https://picsum.photos/seed/studio-04/800/600",
        "https://picsum.photos/seed/studio-05/800/600",
        "https://picsum.photos/seed/studio-06/800/600",
        "https://picsum.photos/seed/studio-07/800/600",
        "https://picsum.photos/seed/studio-08/800/600",
        "https://picsum.photos/seed/studio-09/800/600",
        "https://picsum.photos/seed/studio-10/800/600",
        "https://picsum.photos/seed/studio-11/800/600",
        "https://picsum.photos/seed/studio-12/800/600",
        "https://picsum.photos/seed/studio-13/800/600",
        "https://picsum.photos/seed/studio-14/800/600",
        "https://picsum.photos/seed/studio-15/800/600",
        "https://picsum.photos/seed/studio-16/800/600",
        "https://picsum.photos/seed/studio-17/800/600",
        "https://picsum.photos/seed/studio-18/800/600",
        "https://picsum.photos/seed/studio-19/800/600",
        "https://picsum.photos/seed/studio-20/800/600",
        "https://picsum.photos/seed/studio-21/800/600",
        "https://picsum.photos/seed/studio-22/800/600",
        "https://picsum.photos/seed/studio-23/800/600",
        "https://picsum.photos/seed/studio-24/800/600",
        "https://picsum.photos/seed/studio-25/800/600"
    ],
    "Optics": [
        "https://picsum.photos/seed/optics-01/800/600",
        "https://picsum.photos/seed/optics-02/800/600",
        "https://picsum.photos/seed/optics-03/800/600",
        "https://picsum.photos/seed/optics-04/800/600",
        "https://picsum.photos/seed/optics-05/800/600",
        "https://picsum.photos/seed/optics-06/800/600",
        "https://picsum.photos/seed/optics-07/800/600",
        "https://picsum.photos/seed/optics-08/800/600",
        "https://picsum.photos/seed/optics-09/800/600",
        "https://picsum.photos/seed/optics-10/800/600",
        "https://picsum.photos/seed/optics-11/800/600",
        "https://picsum.photos/seed/optics-12/800/600",
        "https://picsum.photos/seed/optics-13/800/600",
        "https://picsum.photos/seed/optics-14/800/600",
        "https://picsum.photos/seed/optics-15/800/600",
        "https://picsum.photos/seed/optics-16/800/600",
        "https://picsum.photos/seed/optics-17/800/600",
        "https://picsum.photos/seed/optics-18/800/600",
        "https://picsum.photos/seed/optics-19/800/600",
        "https://picsum.photos/seed/optics-20/800/600",
        "https://picsum.photos/seed/optics-21/800/600",
        "https://picsum.photos/seed/optics-22/800/600",
        "https://picsum.photos/seed/optics-23/800/600",
        "https://picsum.photos/seed/optics-24/800/600",
        "https://picsum.photos/seed/optics-25/800/600"
    ],
    "Wear": [
        "https://picsum.photos/seed/wear-01/800/600",
        "https://picsum.photos/seed/wear-02/800/600",
        "https://picsum.photos/seed/wear-03/800/600",
        "https://picsum.photos/seed/wear-04/800/600",
        "https://picsum.photos/seed/wear-05/800/600",
        "https://picsum.photos/seed/wear-06/800/600",
        "https://picsum.photos/seed/wear-07/800/600",
        "https://picsum.photos/seed/wear-08/800/600",
        "https://picsum.photos/seed/wear-09/800/600",
        "https://picsum.photos/seed/wear-10/800/600",
        "https://picsum.photos/seed/wear-11/800/600",
        "https://picsum.photos/seed/wear-12/800/600",
        "https://picsum.photos/seed/wear-13/800/600",
        "https://picsum.photos/seed/wear-14/800/600",
        "https://picsum.photos/seed/wear-15/800/600",
        "https://picsum.photos/seed/wear-16/800/600",
        "https://picsum.photos/seed/wear-17/800/600",
        "https://picsum.photos/seed/wear-18/800/600",
        "https://picsum.photos/seed/wear-19/800/600",
        "https://picsum.photos/seed/wear-20/800/600",
        "https://picsum.photos/seed/wear-21/800/600",
        "https://picsum.photos/seed/wear-22/800/600",
        "https://picsum.photos/seed/wear-23/800/600",
        "https://picsum.photos/seed/wear-24/800/600",
        "https://picsum.photos/seed/wear-25/800/600"
    ],
    "Lifestyle": [
        "https://picsum.photos/seed/life-01/800/600",
        "https://picsum.photos/seed/life-02/800/600",
        "https://picsum.photos/seed/life-03/800/600",
        "https://picsum.photos/seed/life-04/800/600",
        "https://picsum.photos/seed/life-05/800/600",
        "https://picsum.photos/seed/life-06/800/600",
        "https://picsum.photos/seed/life-07/800/600",
        "https://picsum.photos/seed/life-08/800/600",
        "https://picsum.photos/seed/life-09/800/600",
        "https://picsum.photos/seed/life-10/800/600",
        "https://picsum.photos/seed/life-11/800/600",
        "https://picsum.photos/seed/life-12/800/600",
        "https://picsum.photos/seed/life-13/800/600",
        "https://picsum.photos/seed/life-14/800/600",
        "https://picsum.photos/seed/life-15/800/600",
        "https://picsum.photos/seed/life-16/800/600",
        "https://picsum.photos/seed/life-17/800/600",
        "https://picsum.photos/seed/life-18/800/600",
        "https://picsum.photos/seed/life-19/800/600",
        "https://picsum.photos/seed/life-20/800/600",
        "https://picsum.photos/seed/life-21/800/600",
        "https://picsum.photos/seed/life-22/800/600",
        "https://picsum.photos/seed/life-23/800/600",
        "https://picsum.photos/seed/life-24/800/600",
        "https://picsum.photos/seed/life-25/800/600"
    ]
};

const generatedProducts = Array.from({ length: 200 }, (_, index) => {
    const i = index + 1;
    const category = targetCategories[i % targetCategories.length];
    const brand = brands[i % brands.length];
    
    // Select image from category pool with a large enough cycle
    const pool = categoryImages[category] || categoryImages['Lifestyle'];
    const image = pool[Math.floor(index / targetCategories.length) % pool.length];

    return {
        name: `${category} Premium Model ${i}`,
        image,
        description: `This is a high-quality, premium batch generated ${category.toLowerCase()} product designed for performance and reliability.`,
        brand,
        category,
        price: 50 + (i % 300) + 0.99,
        originalPrice: 70 + (i % 300) + 0.99,
        discountPercentage: 10 + (i % 15),
        countInStock: 20 + (i % 80),
        rating: 4.0 + ((i % 10) / 10),
        numReviews: 15 + (i % 200),
        specifications: { 'Quality': 'Premium Grade', 'Edition': `Batch ${i}` }
    };
});

const finalProducts = [...products, ...generatedProducts];

export default finalProducts;
